/*

 FLY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : C:\Users\user\Desktop\My Programs\GrubGlide!\Assets\Letters.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define FlyWidth 20
#define FlyHeight 3
#define FlyBank 0

extern unsigned char Fly[];

/* End of FLY.H */
